routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/stds');
});
Route::resource('stds','StdController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/std.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class std extends Model
{
    protected $fillable = [
        'stdName', 'facilities', 'phone',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/StdController.php
<?php

namespace App\Http\Controllers;

use App\std;
use Illuminate\Http\Request;


class StdController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $stds = std::all();
        return view('stds.index',compact('stds'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('stds.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'stdName'=> 'required|max:15',
            'facilities'=> 'required|max:50',
            'phone'=> 'required|min:9|max:9'
        ]);

        // $stds = new std;
        // $stds->stdName = $request->input('stdName');
        // $stds->facilities = $request->input('facilities');
        // $stds->phone = $request->input('phone');
        // $stds->save();
        $stds = new std([
            'stdName' => $request->input('stdName'),
            'facilities' => $request->input('facilities'),
            'phone' => $request->get('phone'),   
        ]);

        $stds->save();

        return redirect('/stds')->with('success', 'Студент успешно добавлен!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\std  $std
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $std = std::find($id);

        return view('stds.show', compact('std'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\std  $std
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $std =std::find($id);
        return view('stds.edit',compact('std'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\std  $std
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'stdName'=> 'required|max:30',
            'facilities'=> 'required|max:30',
            'phone'=> 'required|max:9|min:9'
        ]);

        $std = std::find($id);
        $std->stdName = $request->get('stdName');
        $std->facilities = $request->get('facilities');
        $std->phone = $request->get('phone');
        $std->save();

        return redirect('/stds')->with('success', 'Анкета успешно отредактирована!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\std  $std 
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $std=std::find($id);
        $std->delete();
        return redirect('/stds')->with('success','Студент успешно удален!');
    }

}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title>@yield('title')</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-success mb-3">
    <div class="container">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">StudentsCRUD</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                <a class="nav-link" href="{{route('stds.index')}}">Studen list</a>
                </li>
            </ul>
           
            </div>
    </div>
    </nav>


     <div class="container">
        @yield('content')

    </div>


<script src="{{ asset('js/app.js') }}"> </script>
</body>
</html>

resources/views/stds/create.blade.php
@extends('layouts.app')

@section('title', 'Добавить Студента')

@section('content')
<div class="row">
    <div class="col-lg-5 mx-auto">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
        <form method="POST" action="{{ route('stds.store') }}">
        @csrf
        <div class="form-group">
            <label for="std-stdName" class="form-label">Имя Студента</label>
            <input type="text" name="stdName" class="form-control" id="std-stdName" >
        
        </div>

        <div class="form-group">
            <label for="std-facilities" class="form-label">Факультет</label>
            <input type="text" name ="facilities" class="form-control" id="std-facilities">
        </div>
        
        <div class="form-group">
            <label for="std-phone" class="form-label">Номера</label>
         

            <input type="text" name="phone" onkeypress="return (event.charCode !=8 && event.charCode ==0 || (event.charCode >= 48 && event.charCode <= 57))" type="number" id="std-phone" name="phone" class="form-control" placeholder="123-456-678" required>
        </div>

        <button type="submit" class="btn btn-success">Создать анкету</button>

        </form>
    </div>
</div>
@endsection

resources/views/stds/edit.blade.php
@extends('layouts.app')

@section('stdName', 'Редактировать Анкету '.$std->stdName)

@section('content')
<div class="row">
<div class="col-lg-6 mx-auto">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div>
    @endif

    <form method="POST" action="{{ route('stds.update', $std) }}">
     @csrf
     @method('PATCH') 
     <div class="form-group">
            <label for="std-stdName" class="form-label">Имя Студента</label>
            <input type="text" value="{{ $std->stdName }}" name="stdName" class="form-control" id="std-stdName" >
        
        </div>

        <div class="form-group">
            <label for="std-facilities" class="form-label">Факультет</label>
            <input type="text" value="{{ $std->facilities }}" name ="facilities" class="form-control" id="std-facilities">
        </div>
        
        <div class="form-group">
            <label for="std-phone" class="form-label">Номера</label>
         

            <input type="text" name="phone" onkeypress="return (event.charCode !=8 && event.charCode ==0 || (event.charCode >= 48 && event.charCode <= 57))" type="number" id="std-phone" name="phone" class="form-control" placeholder="123-456-678" required value="{{ $std->phone }}">
        </div>
        <button type="submit" class="btn btn-success">Отредактировать</button>
    </form>
</div>
</div>
@endsection

resources/views/stds/index.blade.php
@extends('layouts.app')

@section('title', 'Page Title')

@section('content')
<a href="{{ route('stds.create') }}" class="btn btn-success">Добавить студента</a>


<table class="table table-striped mt-2">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Имя</th>
      <th scope="col">Факультет</th>
      <th scope="col">Телефон</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  @foreach($stds as $std) 
    <tr>

      <th scope="row">{{ $std->id }}</th>
      <td>{{ $std->stdName }}</td>
      <td>{{ $std->facilities }}</td>
      <td>{{ $std->phone }}</td>
      <td class="table-buttons">
        <a href="{{ route('stds.show',$std) }}" class="btn btn-success">
            <i class="fa fa-eye" ></i>
        </a>
        <a href="{{ route('stds.edit',$std) }}" class="btn btn-primary">
            <i class="fa fa-pencil" ></i>
        </a>
        <form method="Post" action="{{ route('stds.destroy', $std) }}"">
        @csrf
        @method('DELETE')
        <button type ="submit" class="btn btn-danger" >
            <i class="fa fa-trash"></i>
        </button>
        </form>
      </td>

    </tr>
    @endforeach
  </tbody>
</table>
@endsection

resources/views/stds/show.blade.php
@extends('layouts.app')

@section('title', $std->stdName)

@section('content')
<div class="card">
    <div class="card-body">
       <h3>{{ $std->stdName }}</h3>
       <p>{{ $std->facilities }}</p>
       <p><b>{{ $std->phone }}</b></p>
    </div>
</div>
@endsection